const PES_STATUS = {
  READY: "ready",
  COMMAND_SENT: "command_sent",
  EN_ROUTE: "en_route",
  CONNECTED: "connected",
  REPAIR: "repair",
};

const seedItems = [
  {
    id: "pes-001",
    number: "001",
    name: "Д_Х732УН_№01",
    branch: "Мытищинский филиал",
    po: "Мытищинское ПО",
    powerKw: 508,
    model: "FG Wilson P635",
    status: PES_STATUS.READY,
    baseAddress: "г. Мытищи, ул. Угольная, д.1",
    dispatcherPhone: "+7 (916) 800-85-46",
  },
  {
    id: "pes-002",
    number: "002",
    name: "Д_С240АО_№02",
    branch: "Одинцовский филиал",
    po: "Наро-Фоминское ПО",
    powerKw: 480,
    model: "JCB G660BV05",
    status: PES_STATUS.READY,
    baseAddress: "г. Наро-Фоминск, ул. Московская, д.9",
    dispatcherPhone: "+7 (999) 500-62-79",
  },
  {
    id: "pes-003",
    number: "003",
    name: "Д_О090ОС_№03",
    branch: "Раменский филиал",
    po: "Люберецкое ПО",
    powerKw: 96,
    model: "SDMO J130K",
    status: PES_STATUS.REPAIR,
    baseAddress: "п. Томилино, ул. Лермонтова, д.6",
    dispatcherPhone: "+7 (985) 317-45-53",
  },
  {
    id: "pes-004",
    number: "004",
    name: "Д_М389ТК_№04",
    branch: "Щелковский филиал",
    po: "Ногинское ПО",
    powerKw: 508,
    model: "FG Wilson P635P5",
    status: PES_STATUS.COMMAND_SENT,
    commandSentAt: Date.now() - 6 * 60 * 1000,
    destination: {
      type: "assembly",
      id: "asm-noginsk-1",
      title: "Ногинское ПО — Производственная база",
      address: "г. Ногинск, ул. 1-я Ревсобраний, д.13",
      lat: 55.855,
      lon: 38.441,
    },
    baseAddress: "г. Ногинск, ул. 1-я Ревсобраний, д.13",
    dispatcherPhone: "+7 (916) 409-70-24",
  },
  {
    id: "pes-005",
    number: "005",
    name: "Д_Е146РН_№05",
    branch: "Щелковский филиал",
    po: "Фрязинское ПО",
    powerKw: 100,
    model: "MOTOR АД100-Т400",
    status: PES_STATUS.EN_ROUTE,
    commandSentAt: Date.now() - 27 * 60 * 1000,
    actualDepartureAt: Date.now() - 10 * 60 * 1000,
    destination: {
      type: "tp",
      id: "tp-1001",
      title: "ТП-1001",
      address: "г. Фрязино, ул. Полевая, д.7",
      lat: 55.9635,
      lon: 38.0444,
    },
    baseAddress: "г. Фрязино, ул. Садовая, д.18",
    dispatcherPhone: "+7 (916) 409-70-24",
  },
  {
    id: "pes-006",
    number: "006",
    name: "Д_С440АВ_№06",
    branch: "Коломенский филиал",
    po: "Луховицкое ПО",
    powerKw: 508,
    model: "FG Wilson P635",
    status: PES_STATUS.CONNECTED,
    commandSentAt: Date.now() - 48 * 60 * 1000,
    actualDepartureAt: Date.now() - 33 * 60 * 1000,
    connectedAt: Date.now() - 8 * 60 * 1000,
    destination: {
      type: "tp",
      id: "tp-2077",
      title: "ТП-2077",
      address: "г. Луховицы, ул. Куйбышева, д. 3",
      lat: 54.964,
      lon: 39.026,
    },
    baseAddress: "г. Луховицы, ул. Куйбышева, д.3А",
    dispatcherPhone: "+7 (916) 390-92-37",
  },
];

const assemblyPoints = [
  {
    id: "asm-myt-1",
    branch: "Мытищинский филиал",
    po: "Мытищинское ПО",
    title: "Мытищинское ПО — Производственная база",
    address: "г. Мытищи, ул. Угольная, д.1",
    lat: 55.9112,
    lon: 37.7434,
    dispatcherPhone: "+7 (916) 800-85-46",
  },
  {
    id: "asm-dom-1",
    branch: "Домодедовский филиал",
    po: "Домодедовское ПО",
    title: "Домодедовское ПО — Производственная база",
    address: "г. Домодедово, мкр. Северный, ул. Дачная, д. 2",
    lat: 55.431279,
    lon: 37.749939,
    dispatcherPhone: "+7 (985) 256-83-64",
  },
  {
    id: "asm-kol-1",
    branch: "Коломенский филиал",
    po: "Воскресенское ПО",
    title: "Воскресенское ПО — Производственная база",
    address: "г. Воскресенск, ул. Куйбышева, д. 87",
    lat: 55.314899,
    lon: 38.686594,
    dispatcherPhone: "+7 (915) 214-71-27",
  },
  {
    id: "asm-odn-1",
    branch: "Одинцовский филиал",
    po: "Наро-Фоминское ПО",
    title: "Наро-Фоминское ПО — Производственная база",
    address: "г. Наро-Фоминск, ул. Московская, д.9",
    lat: 55.3866,
    lon: 36.7264,
    dispatcherPhone: "+7 (999) 500-62-79",
  },
];

const tpPoints = [
  {
    id: "tp-1001",
    branch: "Щелковский филиал",
    po: "Фрязинское ПО",
    title: "ТП-1001",
    address: "г. Фрязино, ул. Полевая, д.7",
    lat: 55.9635,
    lon: 38.0444,
  },
  {
    id: "tp-2077",
    branch: "Коломенский филиал",
    po: "Луховицкое ПО",
    title: "ТП-2077",
    address: "г. Луховицы, ул. Куйбышева, д. 3",
    lat: 54.964,
    lon: 39.026,
  },
  {
    id: "tp-3002",
    branch: "Мытищинский филиал",
    po: "Мытищинское ПО",
    title: "ТП-3002",
    address: "г. Мытищи, ул. Колпакова, д.20",
    lat: 55.914,
    lon: 37.735,
  },
];

module.exports = {
  PES_STATUS,
  seedItems,
  assemblyPoints,
  tpPoints,
};
